/**
 * Created by stevenwestermire on 8/10/17.
 */

export const VIEW_STORE = {
    COMPANY_INFO: 'COMPANY_INFO',
    MARKETS: 'MARKETS',
    COMPETITORS: 'COMPETITORS',
    RESEARCH: 'RESEARCH',
    PROPERTIES: 'PROPERTIES',
    WORLD_MAP: 'WORLD_MAP'
};

export const CONST_TO_BE_DEPRECATED = {
    SAN_FRANCISCO: 'SAN_FRANCISCO'
};


//TODO-1: Probably should rename this to Indexed_DB_Tables
export const TABLE_NAMES = {
    PLAYERS: 'PLAYERS',
    PLAYERS_HISTORY: 'PLAYERS_HISTORY',
    FACTORIES: 'FACTORIES',
    CITIES: 'CITIES',
    PRODUCTS: 'PRODUCTS',
    PURCHASE_RESOURCE_TICKETS: 'PURCHASE_RESOURCE_TICKETS',
    SALE_RESOURCE_TICKETS: 'SALE_RESOURCE_TICKETS',
    COMPLETED_TRANSACTIONS: 'COMPLETED_TRANSACTIONS'
};

